
version: 2

# YAML anchors/aliases. See;
# - https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
# - https://github.com/circleci/frontend/blob/master/.circleci/config.yml
references:
  common_config: &common_config
    working_directory: /var/www/code
    docker:
      # @see https://github.com/massgov/Drupal-Container
      - image: massgov/drupal-container:1.0.1-ci

jobs:
  build:
    <<: *common_config
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Cache
          keys:
            - site-npm-v1-{{ checksum "styleguide/yarn.lock" }}
            - site-npm-v1-
      - run: { name: 'NPM Install', command: 'cd styleguide && yarn' }
      - save_cache:
          name: Save NPM cache
          key: site-npm-v1-{{ checksum "styleguide/yarn.lock" }}
          paths: [ styleguide/node_modules ]
      - run: { name: 'Generate style guide', command: 'php styleguide/core/console --generate' }
      - run: { name: 'Build assets', command: 'cd styleguide && node_modules/.bin/gulp prod' }
      - persist_to_workspace:
          root: /var/www
          paths: [code]
      - store_artifacts:
          path: /var/www/code/styleguide/public/assets

  test:
    working_directory: /home/circleci
    docker:
      - image: circleci/python:2.7.14
    environment:
      COMPOSE_FILE: docker-compose.ci.yml
    steps:
      - attach_workspace: {at: /home/circleci}
      - setup_remote_docker
      - run: cd code && docker-compose up --no-start web backstop
      - run: |
          cd code
          docker cp ./ $(docker-compose ps -q backstop):/src/
          docker cp ./styleguide/public $(docker-compose -f docker-compose.ci.yml ps -q web):/usr/share/nginx/html
      - run: cd code && docker-compose run backstop test
      - run:
          command: |
            cd code
            docker-compose run --entrypoint=/bin/ls backstop /src/backstop
            docker-compose run --entrypoint=/bin/ls backstop /src/backstop/reports
            docker cp $(docker-compose ps -q backstop):/src/backstopjs/ ./backstopjs/
          when: always
      - store_artifacts:
          path: /src/code/backstopjs

  deploy_artifacts:
    <<: *common_config
    steps:
      - attach_workspace: {at: /var/www}
      - run:
          name: "Prepare Git"
          command: |
            git config --global user.email "devops@palantir.net"
            git config --global user.name "palantirnet-temp1"
      # @todo: We shouldn't need global gulp from the build scripts.
      - run: { name: 'Gulp Install', command: 'yarn global add gulp' }
      - run: { name: 'Deploy', command: 'cd styleguide && vendor/bin/phing deploy' }

  deploy_cd:
    <<: *common_config
    steps:
      - attach_workspace: {at: /var/www}
      # @todo: We shouldn't need global gulp from the build scripts.
      - run: { name: 'Gulp Install', command: 'yarn global add gulp' }
      - run: { name: 'S3 Deployment', command: 'cd styleguide && ../scripts/deploy-s3.sh -b ${CIRCLE_BRANCH}' }

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - test:
          requires: [build]
      - deploy_artifacts:
          requires: [build]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z\-]+(?:\.[\da-z\-]+)*)?(?:\+[\da-z\-]+(?:\.[\da-z\-]+)*)?\b/
      - deploy_cd:
          requires: [build]
          filters:
            branches:
              ignore: /^master$/