
version: 2

jobs:
  build:
    working_directory: /var/www/code
    docker:
      - image: massgov/drupal-container:1.0.1-ci
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Cache
          keys:
            - site-npm-v1-{{ checksum "styleguide/package.json" }}
            - site-npm-v1-
      - run: { name: 'NPM Install', command: 'cd styleguide && yarn' }
      - save_cache:
          name: Save NPM cache
          key: site-npm-v1-{{ checksum "styleguide/package.json" }}
          paths: [ styleguide/node_modules ]
      - run: { name: 'Generate style guide', command: 'php styleguide/core/console --generate' }
      - run: { name: 'Build assets', command: 'cd styleguide && node_modules/.bin/gulp prod' }
      - store_artifacts:
          path: /var/www/code/styleguide/public/assets

